class_name ArmorForge
extends RefCounted
## Builds the high-detail hero models: full plate armour sculpted from lathed
## plates, lames, domes, spikes and blades, riding the bones of the rigged
## source character (so every existing animation keeps working) with
## realistic proportions from HeroicRig. The chibi source meshes are hidden.
##
## Materials are PBR texture sets (assets/textures/armor/*, generated by
## tools/design/gen_armor_textures.py) through armor_pbr.gdshader.
## Meshes are cached per design, materials are per model instance (so hit
## flash / freeze / dissolve stay per unit). Small details (rivets) sit in a
## separate mesh with a visibility range (LOD).
##
## Bone frames of the source rig: torso / head bones are Y up, Z forward.
## Arm bones run along +Y, local +Z is up in T-pose, forward is +X on the left
## arm and -X on the right. Leg bones run down along +Y with front = -Z.

const TEX := "res://assets/textures/armor/%s_%s.png"

static var _mesh_cache: Dictionary = {}


# ================================================================ entry
static func has_design(id: String) -> bool:
	return id in ["hell_knight"]


static func build(model: CharacterModel, skel: Skeleton3D, inst: Node3D, def: Dictionary) -> void:
	var design := str(def.forge)
	var rig := HeroicRig.make(def.get("rig", {}))
	skel.add_child(rig)
	inst.position.y += rig.leg_lift(skel) * 0.985
	var mats := _materials(def)
	for m in mats.values():
		model.materials.append(m)
	var parts: Dictionary = _mesh_cache.get(design, {})
	if parts.is_empty():
		match design:
			"hell_knight": parts = _hell_knight()
		_mesh_cache[design] = parts
	for bone in parts:
		if skel.find_bone(bone) < 0:
			continue
		var att := BoneAttachment3D.new()
		att.bone_name = bone
		att.set_meta("gear", true)
		skel.add_child(att)
		var entry: Dictionary = parts[bone]
		for layer in ["main", "detail"]:
			if not entry.has(layer):
				continue
			var mesh: ArrayMesh = entry[layer].mesh
			var keys: Array = entry[layer].keys
			var mi := MeshInstance3D.new()
			mi.mesh = mesh
			for si in keys.size():
				mi.set_surface_override_material(si, mats[keys[si]])
			if layer == "detail":
				# LOD: rivets and fine trims fade out when the camera is far away.
				mi.visibility_range_end = 34.0
				mi.visibility_range_end_margin = 6.0
				mi.visibility_range_fade_mode = GeometryInstance3D.VISIBILITY_RANGE_FADE_SELF
				mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
			att.add_child(mi)
	match design:
		"hell_knight": _hell_knight_fx(skel, def)


# ================================================================ materials
static func _tex_set(key: String) -> Dictionary:
	return {"albedo_map": load(TEX % [key, "albedo"]), "normal_map": load(TEX % [key, "normal"]),
		"roughness_map": load(TEX % [key, "roughness"]), "metallic_map": load(TEX % [key, "metallic"])}


static func _mat(maps: Dictionary, params: Dictionary) -> ShaderMaterial:
	var m := ShaderMaterial.new()
	m.shader = load("res://assets/shaders/armor_pbr.gdshader")
	for k in maps:
		m.set_shader_parameter(k, maps[k])
	for k in params:
		m.set_shader_parameter(k, params[k])
	return m


static func _materials(def: Dictionary) -> Dictionary:
	var glow := ModelLib._col(def.get("emission", [1, 0.35, 0.06]))
	var steel := _tex_set("dark_steel")
	var inf := _tex_set("infernal_steel")
	inf["emission_map"] = load(TEX % ["infernal_steel", "emission"])
	var leather := _tex_set("leather")
	var cloth := _tex_set("cloth")
	var common := {"glow_color": glow, "glow_strength": float(def.get("emission_strength", 1.5)), "rim_strength": 0.06}
	var out := {}
	out["steel"] = _mat(steel, common.merged({"tint": Color(0.86, 0.88, 0.95), "albedo_gain": 1.7, "tile": 3.2, "normal_strength": 1.3, "roughness_mul": 0.8, "metallic_mul": 0.62, "edge_wear": 0.9}))
	out["infernal"] = _mat(inf, common.merged({"tint": Color(0.9, 0.88, 0.92), "albedo_gain": 1.6, "metallic_mul": 0.62, "roughness_mul": 0.8, "edge_wear": 0.8, "tile": 2.2, "emission_color": glow, "emission_energy": 4.0, "normal_strength": 1.2}))
	out["gold"] = _mat(steel, common.merged({"tint": Color(3.2, 2.1, 0.8), "albedo_gain": 3.0, "tile": 4.0, "roughness_mul": 0.75, "metallic_mul": 1.1, "edge_wear": 0.6}))
	out["leather"] = _mat(leather, common.merged({"tint": Color(0.7, 0.55, 0.5), "albedo_gain": 3.2, "tile": 4.0, "edge_wear": 0.0}))
	out["cloth"] = _mat(cloth, common.merged({"tint": Color(0.16, 0.03, 0.03), "tile": 3.0, "edge_wear": 0.0}))
	out["glow"] = _mat(leather, common.merged({"tint": Color(0, 0, 0), "emission_color": glow, "flat_emission": 2.4, "edge_wear": 0.0, "rim_strength": 0.0}))
	return out


# ================================================================ mesh kit
class Kit:
	var st: Dictionary = {}      # material key -> SurfaceTool
	var counts: Dictionary = {}

	func _tool(key: String) -> SurfaceTool:
		if not st.has(key):
			var t := SurfaceTool.new()
			t.begin(Mesh.PRIMITIVE_TRIANGLES)
			st[key] = t
			counts[key] = 0
		return st[key]

	## Surface of revolution around local Y. profile: Vector2(r, y) or
	## Vector3(rx, y, rz). Angles a0..a1 (0 = +X, PI/2 = +Z).
	func lathe(key: String, profile: Array, seg: int, xf := Transform3D.IDENTITY, sx := 1.0, sz := 1.0, a0 := 0.0, a1 := TAU, cap := false) -> void:
		var t := _tool(key)
		var base: int = counts[key]
		var rows := profile.size()
		var closed := absf(a1 - a0 - TAU) < 0.001
		var cols := seg + 1
		var pts: Array = []
		for p in profile:
			var v: Vector3 = Vector3(p.x, p.y, p.x) if p is Vector2 else p
			pts.append(v)
		for i in rows:
			var v: Vector3 = pts[i]
			var prev: Vector3 = pts[maxi(0, i - 1)]
			var nxt: Vector3 = pts[mini(rows - 1, i + 1)]
			for j in cols:
				var a := a0 + (a1 - a0) * float(j) / float(seg)
				var c := cos(a)
				var s := sin(a)
				var pos := Vector3(c * v.x * sx, v.y, s * v.z * sz)
				# Analytic normal: ring tangent x profile tangent, facing outward.
				var tr := Vector3(-s * v.x * sx, 0, c * v.z * sz)
				var p0 := Vector3(c * prev.x * sx, prev.y, s * prev.z * sz)
				var p1 := Vector3(c * nxt.x * sx, nxt.y, s * nxt.z * sz)
				var tp := p1 - p0
				var n := tr.cross(tp)
				if n.length_squared() < 1e-12:
					n = Vector3(c, 0, s) if v.y > 0 else Vector3(c, 0, s)
				var radial := Vector3(c * sx, 0, s * sz)
				if n.dot(radial) < 0.0:
					n = -n
				if tr.length_squared() < 1e-10:        # apex
					n = Vector3(0, signf(v.y - prev.y) if v.y != prev.y else 1.0, 0)
				t.set_normal((xf.basis * n).normalized())
				t.set_uv(Vector2(float(j) / seg, float(i) / maxi(1, rows - 1)))
				t.add_vertex(xf * pos)
		for i in rows - 1:
			for j in seg:
				var a := base + i * cols + j
				var b := a + 1
				var c2 := a + cols
				var d := c2 + 1
				t.add_index(a); t.add_index(c2); t.add_index(b)
				t.add_index(b); t.add_index(c2); t.add_index(d)
		counts[key] = base + rows * cols
		if cap and closed:
			var top: Vector3 = pts[rows - 1]
			var ci: int = counts[key]
			t.set_normal((xf.basis * Vector3.UP).normalized())
			t.set_uv(Vector2(0.5, 1))
			t.add_vertex(xf * Vector3(0, top.y, 0))
			var first := base + (rows - 1) * cols
			for j in seg:
				t.add_index(ci); t.add_index(first + j); t.add_index(first + j + 1)
			counts[key] = ci + 1

	## Axis-aligned (in xf) box with flat faces.
	func box(key: String, c: Vector3, size: Vector3, xf := Transform3D.IDENTITY) -> void:
		var t := _tool(key)
		var h := size * 0.5
		var faces := [[Vector3.RIGHT, Vector3.UP, Vector3.BACK], [Vector3.LEFT, Vector3.UP, Vector3.FORWARD],
			[Vector3.UP, Vector3.BACK, Vector3.RIGHT], [Vector3.DOWN, Vector3.FORWARD, Vector3.RIGHT],
			[Vector3.BACK, Vector3.UP, Vector3.LEFT], [Vector3.FORWARD, Vector3.UP, Vector3.RIGHT]]
		for f in faces:
			var n: Vector3 = f[0]
			var u: Vector3 = f[1]
			var v: Vector3 = f[2]
			var base: int = counts[key]
			for k in 4:
				var su := -1.0 if k == 0 or k == 3 else 1.0
				var sv := -1.0 if k < 2 else 1.0
				var p := c + n * h + u * h * su + v * h * sv    # component-wise with the half size
				t.set_normal((xf.basis * n).normalized())
				t.set_uv(Vector2(su, sv) * 0.5 + Vector2(0.5, 0.5))
				t.add_vertex(xf * p)
			t.add_index(base); t.add_index(base + 1); t.add_index(base + 2)
			t.add_index(base); t.add_index(base + 2); t.add_index(base + 3)
			counts[key] = base + 4

	## Cone / spike from `base` along `dir`.
	func spike(key: String, base: Vector3, dir: Vector3, r: float, h: float, xf := Transform3D.IDENTITY, seg := 8) -> void:
		lathe(key, [Vector2(r, 0), Vector2(r * 0.55, h * 0.45), Vector2(0.0, h)], seg, xf * Transform3D(ArmorForge.basis_y(dir), base))

	## Curved horn: tapering segments bending by `bend` (radians per segment around `axis`).
	func horn(key: String, base: Vector3, dir: Vector3, bend_axis: Vector3, r: float, seg_len: float, segments: int, bend: float, xf := Transform3D.IDENTITY) -> void:
		var p := base
		var d := dir.normalized()
		var rr := r
		for k in segments:
			var r1 := rr * 0.72 if k < segments - 1 else 0.0
			lathe(key, [Vector2(rr, 0), Vector2(r1, seg_len)], 9, xf * Transform3D(ArmorForge.basis_y(d), p))
			p += d * seg_len * 0.96
			d = d.rotated(bend_axis.normalized(), bend)
			rr = r1

	func commit() -> Dictionary:
		var mesh := ArrayMesh.new()
		var keys: Array = []
		for k in st:
			var t: SurfaceTool = st[k]
			t.commit(mesh)
			keys.append(k)
		return {"mesh": mesh, "keys": keys}


static func basis_y(dir: Vector3) -> Basis:
	var y := dir.normalized()
	var ref := Vector3.FORWARD if absf(y.dot(Vector3.UP)) > 0.95 else Vector3.UP
	var x := ref.cross(y).normalized()
	var z := x.cross(y).normalized()
	return Basis(x, y, z)


static func _pack(main: Kit, detail: Kit = null) -> Dictionary:
	var out := {"main": main.commit()}
	if detail and not detail.st.is_empty():
		out["detail"] = detail.commit()
	return out


# ================================================================ HELL KNIGHT
## Blackened plate with lava-cracked infernal plates, a horned great helm with
## a burning visor, spiked pauldrons, a flaming two-handed greatsword and a
## spiked kite shield slung on the back.
static func _hell_knight() -> Dictionary:
	var parts := {}
	var X := Transform3D.IDENTITY
	# ---------------- hips: belt, fauld, rear lames
	var k := Kit.new()
	var d := Kit.new()
	k.lathe("leather", [Vector2(0.19, -0.02), Vector2(0.2, 0.1), Vector2(0.2, 0.24)], 20, X, 1.15, 0.9)
	k.lathe("steel", [Vector2(0.212, 0.155), Vector2(0.222, 0.172), Vector2(0.222, 0.212), Vector2(0.212, 0.23)], 24, X, 1.15, 0.92)
	k.box("gold", Vector3(0, 0.192, 0.215), Vector3(0.09, 0.075, 0.03))
	k.box("infernal", Vector3(0, 0.192, 0.232), Vector3(0.045, 0.04, 0.012))
	for i in 3:
		var y0 := 0.16 - i * 0.058
		k.lathe("steel", [Vector2(0.214 + i * 0.012, y0), Vector2(0.226 + i * 0.013, y0 - 0.045), Vector2(0.236 + i * 0.014, y0 - 0.085)], 18, X, 1.15, 0.96, PI * 0.5 - 1.85, PI * 0.5 + 1.85)
		k.lathe("steel", [Vector2(0.214 + i * 0.012, y0), Vector2(0.236 + i * 0.014, y0 - 0.08)], 12, X, 1.15, 0.96, -PI * 0.5 - 1.1, -PI * 0.5 + 1.1)
	for i in 6:
		var a := PI * 0.5 - 1.5 + i * 0.6
		d.lathe("gold", [Vector2(0.012, -0.006), Vector2(0.012, 0.0), Vector2(0.0, 0.008)], 6, Transform3D(basis_y(Vector3(cos(a) * 1.15, 0, sin(a) * 0.92)), Vector3(cos(a) * 0.25, 0.192, sin(a) * 0.205)))
	parts["hips"] = _pack(k, d)
	# ---------------- spine: abdomen lames
	k = Kit.new()
	k.lathe("leather", [Vector2(0.19, -0.02), Vector2(0.2, 0.2), Vector2(0.215, 0.38)], 20, X, 1.1, 0.85)
	for i in 3:
		var y1 := 0.02 + i * 0.09
		k.lathe("steel", [Vector2(0.205 + i * 0.006, y1), Vector2(0.214 + i * 0.006, y1 + 0.05), Vector2(0.212 + i * 0.006, y1 + 0.105)], 20, X, 1.12, 0.9, PI * 0.5 - 2.0, PI * 0.5 + 2.0)
	parts["spine"] = _pack(k)
	# ---------------- chest: breastplate, sigil, gorget, back shield
	k = Kit.new()
	d = Kit.new()
	var bp := [Vector2(0.21, -0.08), Vector2(0.236, 0.0), Vector2(0.256, 0.09), Vector2(0.25, 0.17), Vector2(0.21, 0.232), Vector2(0.15, 0.272)]
	k.lathe("steel", bp, 28, Transform3D(Basis.IDENTITY, Vector3(0, 0, 0.012)), 1.18, 0.9)
	k.lathe("gold", [Vector2(0.212, -0.085), Vector2(0.214, -0.07)], 28, Transform3D(Basis.IDENTITY, Vector3(0, 0, 0.012)), 1.19, 0.91)
	# central ridge and the burning sigil
	k.lathe("steel", [Vector3(0.0, -0.07, 0.0), Vector3(0.012, -0.04, 0.02), Vector3(0.012, 0.18, 0.02), Vector3(0.0, 0.23, 0.0)], 4, Transform3D(Basis.IDENTITY, Vector3(0, 0, 0.228)))
	k.lathe("infernal", [Vector3(0.0, 0.0, 0.0), Vector3(0.08, 0.075, 0.014), Vector3(0.0, 0.16, 0.0)], 4, Transform3D(Basis.IDENTITY, Vector3(0, 0.0, 0.238)))
	k.lathe("gold", [Vector3(0.0, -0.012, 0.0), Vector3(0.094, 0.075, 0.008), Vector3(0.0, 0.172, 0.0)], 4, Transform3D(Basis.IDENTITY, Vector3(0, 0.0, 0.232)))
	# gorget up to the helm
	k.lathe("steel", [Vector2(0.14, 0.2), Vector2(0.152, 0.25), Vector2(0.132, 0.3), Vector2(0.146, 0.322)], 22, X, 1.1, 1.0)
	k.lathe("gold", [Vector2(0.146, 0.318), Vector2(0.15, 0.332)], 22, X, 1.1, 1.0)
	for i in 8:
		var a := PI * 0.5 + (i - 3.5) * 0.28
		d.lathe("gold", [Vector2(0.01, -0.005), Vector2(0.01, 0.0), Vector2(0.0, 0.007)], 6, Transform3D(basis_y(Vector3(cos(a), 0.2, sin(a))), Vector3(cos(a) * 0.29, 0.165, sin(a) * 0.235)))
	# spiked kite shield on the back
	var sx := Transform3D(Basis.from_euler(Vector3(0.12, PI, 0.0)), Vector3(0.0, 0.02, -0.285))
	k.lathe("steel", [Vector3(0.0, -0.36, 0.0), Vector3(0.12, -0.22, 0.03), Vector3(0.2, 0.0, 0.04), Vector3(0.21, 0.16, 0.035), Vector3(0.16, 0.25, 0.025), Vector3(0.0, 0.27, 0.0)], 14, sx, 1.0, 1.0, -PI * 0.5, PI * 0.5)
	k.lathe("gold", [Vector3(0.0, -0.375, 0.0), Vector3(0.13, -0.225, 0.008), Vector3(0.215, 0.0, 0.01), Vector3(0.225, 0.165, 0.009), Vector3(0.17, 0.26, 0.007), Vector3(0.0, 0.285, 0.0)], 14, sx * Transform3D(Basis.IDENTITY, Vector3(0, 0, -0.002)), 1.0, 1.0, -PI * 0.5, -PI * 0.5 + 0.35)
	k.lathe("infernal", [Vector3(0.0, -0.18, 0.0), Vector3(0.1, -0.02, 0.012), Vector3(0.0, 0.16, 0.0)], 4, sx * Transform3D(Basis.IDENTITY, Vector3(0, 0, 0.04)))
	k.spike("steel", Vector3(0, -0.02, 0.05), Vector3(0, 0, 1), 0.045, 0.16, sx)
	parts["chest"] = _pack(k, d)
	# ---------------- head: horned great helm with burning visor
	k = Kit.new()
	var hp := [Vector2(0.105, -0.02), Vector2(0.13, 0.03), Vector2(0.15, 0.1), Vector2(0.158, 0.17), Vector2(0.152, 0.23), Vector2(0.13, 0.285), Vector2(0.085, 0.325), Vector2(0.03, 0.343), Vector2(0.0, 0.346)]
	var hx := Transform3D(Basis.IDENTITY, Vector3(0, 0, 0.012))
	k.lathe("steel", hp, 28, hx, 0.92, 1.06)
	k.lathe("gold", [Vector2(0.132, 0.02), Vector2(0.138, 0.034), Vector2(0.136, 0.05)], 28, hx, 0.93, 1.07)
	k.lathe("steel", [Vector3(0.0, 0.03, 0.0), Vector3(0.012, 0.06, 0.03), Vector3(0.014, 0.25, 0.03), Vector3(0.0, 0.32, 0.0)], 4, Transform3D(Basis.IDENTITY, Vector3(0, 0, 0.158)))
	k.box("glow", Vector3(0, 0.19, 0.165), Vector3(0.17, 0.018, 0.012))
	k.box("steel", Vector3(0, 0.205, 0.168), Vector3(0.19, 0.012, 0.018))
	for i in 5:
		k.box("glow", Vector3(-0.05 + i * 0.025, 0.11, 0.16), Vector3(0.008, 0.035, 0.01))
	for s in [-1.0, 1.0]:
		k.horn("steel", Vector3(0.12 * s, 0.24, 0.0), Vector3(0.9 * s, 0.5, -0.15), Vector3(0, 0, 1) * -s + Vector3(0, 0.2, 0), 0.045, 0.075, 5, 0.42)
		k.lathe("infernal", [Vector2(0.05, -0.01), Vector2(0.052, 0.02), Vector2(0.046, 0.035)], 10, Transform3D(basis_y(Vector3(0.9 * s, 0.5, -0.15)), Vector3(0.12 * s, 0.24, 0.0)))
	for i in 4:
		k.spike("steel", Vector3(0, 0.33 - i * 0.03, -0.02 - i * 0.05), Vector3(0, 0.6, -0.8), 0.018, 0.1 - i * 0.012)
	parts["head"] = _pack(k)
	# ---------------- arms
	for side in [1.0, -1.0]:
		var sfx := ".l" if side > 0 else ".r"
		var fwd := Vector3(side, 0, 0)          # arm-local forward in T-pose
		# upper arm: rerebrace + big infernal pauldron with lames and spikes
		k = Kit.new()
		d = Kit.new()
		k.lathe("leather", [Vector2(0.055, 0.0), Vector2(0.058, 0.15), Vector2(0.05, 0.3)], 12)
		k.lathe("steel", [Vector2(0.066, 0.07), Vector2(0.07, 0.15), Vector2(0.064, 0.27)], 16)
		var pd := Transform3D(Basis(Vector3.RIGHT, PI * 0.5), Vector3(0, 0.05, 0.02))
		k.lathe("infernal", [Vector2(0.172, -0.06), Vector2(0.168, 0.0), Vector2(0.152, 0.06), Vector2(0.112, 0.11), Vector2(0.05, 0.14), Vector2(0.0, 0.146)], 22, pd, 1.12, 1.3)
		k.lathe("gold", [Vector2(0.175, -0.068), Vector2(0.18, -0.05)], 22, pd, 1.12, 1.3)
		for i in 3:
			var y2 := 0.13 + i * 0.045
			k.lathe("steel", [Vector2(0.118 - i * 0.012, y2), Vector2(0.124 - i * 0.012, y2 + 0.03), Vector2(0.12 - i * 0.012, y2 + 0.058)], 14, X, 1.1, 1.0, PI * 0.5 - 1.75, PI * 0.5 + 1.75)
		for i in 3:
			k.spike("steel", Vector3(0, -0.02 + i * 0.075, 0.15), Vector3(0, 0.15 * (i - 1), 1), 0.03, 0.2 - absf(i - 1) * 0.05)
		for i in 6:
			var a := TAU * i / 6.0
			d.lathe("gold", [Vector2(0.01, -0.004), Vector2(0.0, 0.006)], 6, pd * Transform3D(basis_y(Vector3(cos(a), 0.1, sin(a))), Vector3(cos(a) * 0.18, -0.05, sin(a) * 0.21)))
		parts["upperarm" + sfx] = _pack(k, d)
		# forearm: couter with spike + lava-cracked vambrace with a gold cuff
		k = Kit.new()
		k.lathe("leather", [Vector2(0.05, 0.0), Vector2(0.046, 0.34)], 12)
		var back := -fwd
		k.lathe("steel", [Vector2(0.078, 0.0), Vector2(0.072, 0.035), Vector2(0.042, 0.066), Vector2(0.0, 0.078)], 14, Transform3D(basis_y(back), Vector3(0, 0.0, 0)))
		k.lathe("steel", [Vector3(0.11, -0.004, 0.02), Vector3(0.11, 0.004, 0.02)], 14, Transform3D(basis_y(back), back * 0.03), 1.0, 1.0)
		k.spike("infernal", back * 0.07, back + Vector3(0, 0.3, 0), 0.022, 0.11)
		k.lathe("infernal", [Vector2(0.06, 0.05), Vector2(0.064, 0.12), Vector2(0.058, 0.26), Vector2(0.07, 0.305), Vector2(0.073, 0.33)], 16)
		k.lathe("gold", [Vector2(0.071, 0.295), Vector2(0.075, 0.315), Vector2(0.074, 0.335)], 16)
		parts["lowerarm" + sfx] = _pack(k)
		# gauntlet
		k = Kit.new()
		k.lathe("steel", [Vector2(0.074, -0.085), Vector2(0.064, -0.02), Vector2(0.056, 0.0)], 12)
		k.lathe("steel", [Vector2(0.056, -0.01), Vector2(0.06, 0.05), Vector2(0.05, 0.11)], 4, X, 1.0, 0.62, PI * 0.25, PI * 0.25 + TAU)
		for i in 3:
			k.lathe("steel", [Vector2(0.052 - i * 0.004, 0.11 + i * 0.028), Vector2(0.05 - i * 0.004, 0.132 + i * 0.028)], 4, X, 1.0, 0.6, PI * 0.25, PI * 0.25 + TAU)
		for i in 3:
			k.spike("infernal", Vector3(-0.025 + i * 0.025, 0.085, 0.032), Vector3(0, 0.2, 1), 0.01, 0.035, X, 6)
		parts["hand" + sfx] = _pack(k)
	# ---------------- legs
	for sfx in [".l", ".r"]:
		k = Kit.new()
		k.lathe("leather", [Vector2(0.085, 0.0), Vector2(0.09, 0.2), Vector2(0.075, 0.45)], 14)
		k.lathe("steel", [Vector2(0.1, 0.04), Vector2(0.104, 0.18), Vector2(0.09, 0.4), Vector2(0.094, 0.44)], 18, X, 1.05, 1.0)
		k.lathe("steel", [Vector2(0.125, -0.04), Vector2(0.13, 0.1), Vector2(0.125, 0.2)], 14, X, 1.0, 1.0, -PI * 0.5 - 1.2, -PI * 0.5 + 1.2)
		k.lathe("gold", [Vector2(0.127, 0.195), Vector2(0.13, 0.215)], 14, X, 1.0, 1.0, -PI * 0.5 - 1.2, -PI * 0.5 + 1.2)
		parts["upperleg" + sfx] = _pack(k)
		k = Kit.new()
		k.lathe("leather", [Vector2(0.07, 0.0), Vector2(0.06, 0.43)], 12)
		k.lathe("steel", [Vector2(0.088, 0.0), Vector2(0.082, 0.04), Vector2(0.052, 0.076), Vector2(0.0, 0.088)], 14, Transform3D(Basis(Vector3.RIGHT, -PI * 0.5), Vector3(0, 0.0, -0.025)))
		k.lathe("steel", [Vector3(0.115, -0.005, 0.03), Vector3(0.115, 0.005, 0.03)], 14, Transform3D(Basis(Vector3.RIGHT, -PI * 0.5), Vector3(0, 0.0, -0.035)))
		k.spike("infernal", Vector3(0, 0.02, -0.1), Vector3(0, 0.35, -1), 0.024, 0.11)
		k.lathe("infernal", [Vector2(0.078, 0.06), Vector2(0.083, 0.15), Vector2(0.068, 0.33), Vector2(0.074, 0.42)], 18)
		k.lathe("steel", [Vector3(0.0, 0.07, 0.0), Vector3(0.01, 0.1, 0.018), Vector3(0.01, 0.38, 0.018), Vector3(0.0, 0.42, 0.0)], 4, Transform3D(Basis.IDENTITY, Vector3(0, 0, -0.078)))
		parts["lowerleg" + sfx] = _pack(k)
		k = Kit.new()
		k.lathe("steel", [Vector2(0.068, -0.03), Vector2(0.074, 0.05), Vector2(0.064, 0.14), Vector2(0.042, 0.2), Vector2(0.0, 0.225)], 14, Transform3D(Basis.IDENTITY, Vector3(0, 0, -0.01)), 1.0, 0.72)
		for i in 3:
			k.lathe("gold", [Vector2(0.075 - i * 0.008, 0.04 + i * 0.045), Vector2(0.075 - i * 0.008, 0.05 + i * 0.045)], 14, Transform3D(Basis.IDENTITY, Vector3(0, 0, -0.01)), 1.0, 0.73, PI - 0.2, TAU + 0.2)
		parts["foot" + sfx] = _pack(k)
	# ---------------- greatsword in the right hand (blade along +Y)
	k = Kit.new()
	k.lathe("gold", [Vector2(0.0, -0.43), Vector2(0.036, -0.4), Vector2(0.046, -0.37), Vector2(0.03, -0.335)], 12)
	k.spike("gold", Vector3(0, -0.425, 0), Vector3(0, -1, 0), 0.014, 0.05)
	k.lathe("leather", [Vector2(0.024, -0.34), Vector2(0.027, -0.16), Vector2(0.025, 0.02)], 10)
	for i in 4:
		k.lathe("gold", [Vector2(0.028, -0.3 + i * 0.08), Vector2(0.028, -0.29 + i * 0.08)], 10)
	k.box("steel", Vector3(0, 0.045, 0), Vector3(0.44, 0.05, 0.07))
	k.box("gold", Vector3(0, 0.045, 0), Vector3(0.12, 0.07, 0.085))
	k.lathe("infernal", [Vector2(0.0, -0.012), Vector2(0.03, 0.0), Vector2(0.0, 0.012)], 8, Transform3D(Basis(Vector3.RIGHT, PI * 0.5), Vector3(0, 0.048, 0.045)))
	for s in [-1.0, 1.0]:
		k.spike("infernal", Vector3(0.22 * s, 0.045, 0), Vector3(0.6 * s, 0.8, 0), 0.028, 0.14)
	k.lathe("infernal", [Vector3(0.056, 0.07, 0.022), Vector3(0.07, 0.2, 0.02), Vector3(0.066, 0.9, 0.017), Vector3(0.05, 1.25, 0.014), Vector3(0.0, 1.46, 0.003)], 4, X, 1.0, 1.0, 0.0, TAU)
	for s in [-1.0, 1.0]:
		k.box("glow", Vector3(0, 0.62, 0.0195 * s), Vector3(0.01, 0.95, 0.004))
	parts["handslot.r"] = _pack(k)
	return parts


static func _hell_knight_fx(skel: Skeleton3D, def: Dictionary) -> void:
	# The blade's fire is in its emissive lava cracks and burning edge; a
	# small flickering light makes it cast a warm glow on the armour.
	for c in skel.get_children():
		if c is BoneAttachment3D and c.bone_name == "handslot.r" and c.has_meta("gear"):
			var l := OmniLight3D.new()
			l.light_color = ModelLib._col(def.get("emission", [1, 0.35, 0.06]))
			l.light_energy = 0.6
			l.omni_range = 1.8
			l.light_volumetric_fog_energy = 0.0
			l.position = Vector3(0, 0.8, 0)
			c.add_child(l)
			var f := LightFlicker.new()
			f.light = l
			c.add_child(f)
