class_name HeroTree
extends RefCounted
## Hero Mastery: a permanent, hand-authored skill tree per hero (see
## data/hero_tree.json, generated by tools/design/gen_hero_tree.py).
##
## Points ("Hero Marks") come from the hero's own level — one per level after
## the first plus a bonus every few levels — so old saves are covered
## automatically. Spent marks are recomputed from the owned nodes.
##
## Save format (profile.hero_tree): {"nodes": {hero_id: [node_id, ...]}, "respecs": int}
## This is separate from the older per-hero skill ranks (profile.heroes[id].skills),
## which keep working unchanged.

const STAT_KEYS := ["damage_pct", "health_pct", "defense_pct", "attack_speed", "move_speed", "range_add",
	"crit", "crit_dmg", "lifesteal", "cdr", "energy_regen", "ult_mult", "dr", "thorns", "regen",
	"splash", "multishot", "pierce", "chain", "on_hit_execute", "revive"]

static var _fx_cache: Dictionary = {}


# ---------------------------------------------------------------- state
static func data() -> Dictionary:
	return DB.hero_tree


static func state() -> Dictionary:
	var p: Dictionary = Game.profile
	if not p.has("hero_tree") or typeof(p.hero_tree) != TYPE_DICTIONARY:
		p["hero_tree"] = {}
	var s: Dictionary = p.hero_tree
	if not s.has("nodes"): s["nodes"] = {}
	if not s.has("respecs"): s["respecs"] = 0
	return s


static func hero_ids() -> Array:
	var out: Array = []
	for hid in DB.hero_order:
		if data().get("heroes", {}).has(hid):
			out.append(hid)
	return out


static func hero_level(hero_id: String) -> int:
	var h: Dictionary = Game.profile.get("heroes", {}).get(hero_id, {})
	return int(h.get("level", 1))


static func earned(hero_id: String) -> int:
	var cfg: Dictionary = data().get("points", {})
	var lvl := hero_level(hero_id)
	return maxi(0, (lvl - 1) * int(cfg.get("per_level", 1)) + lvl / maxi(1, int(cfg.get("bonus_every", 5))))


static func spent(hero_id: String) -> int:
	var total := 0
	for nid in owned(hero_id):
		total += int(node(hero_id, nid).get("cost", 0))
	return total


static func available(hero_id: String) -> int:
	return maxi(0, earned(hero_id) - spent(hero_id))


static func nodes(hero_id: String) -> Array:
	return data().get("heroes", {}).get(hero_id, {}).get("nodes", [])


static func node(hero_id: String, node_id: String) -> Dictionary:
	for n in nodes(hero_id):
		if n.id == node_id:
			return n
	return {}


static func owned(hero_id: String) -> Array:
	if Game.profile.is_empty():
		return []
	return state().nodes.get(hero_id, [])


static func has(hero_id: String, node_id: String) -> bool:
	return node_id in owned(hero_id)


## "owned", "available", "no_points", "level", "requires", "blocked"
static func status(hero_id: String, node_id: String) -> String:
	if has(hero_id, node_id):
		return "owned"
	var n := node(hero_id, node_id)
	if n.is_empty():
		return "requires"
	if n.has("exclusive"):
		for o in owned(hero_id):
			if node(hero_id, o).get("exclusive", "") == n.exclusive:
				return "blocked"
	var req: Array = n.get("requires_any", [])
	if not req.is_empty() and not req.any(func(r): return has(hero_id, r)):
		return "requires"
	if hero_level(hero_id) < int(n.get("level", 1)):
		return "level"
	if available(hero_id) < int(n.get("cost", 1)):
		return "no_points"
	return "available"


static func buy(hero_id: String, node_id: String) -> bool:
	if status(hero_id, node_id) != "available":
		return false
	var s := state()
	if not s.nodes.has(hero_id):
		s.nodes[hero_id] = []
	s.nodes[hero_id].append(node_id)
	_changed()
	Events.track("hero_mastery")
	return true


static func respec_cost(hero_id: String) -> int:
	var pts := spent(hero_id)
	if pts <= 0:
		return 0
	var r: Dictionary = data().get("respec", {})
	return maxi(int(r.get("min_gold", 150)), pts * int(r.get("gold_per_point", 60)))


static func respec(hero_id: String) -> bool:
	var cost := respec_cost(hero_id)
	if cost <= 0 or Game.gold() < cost:
		return false
	Game.add_gold(-cost)
	var s := state()
	s.nodes.erase(hero_id)
	s.respecs = int(s.respecs) + 1
	_changed()
	return true


static func has_capstone(hero_id: String) -> bool:
	return owned(hero_id).any(func(n): return node(hero_id, n).get("capstone", false))


static func mastery_tier(hero_id: String) -> int:
	var o := owned(hero_id)
	if o.is_empty():
		return 0
	if has_capstone(hero_id):
		return 3
	if o.any(func(n): return n in ["a1", "b1"]):
		return 2
	return 1


static func chosen_path(hero_id: String) -> String:
	if has(hero_id, "a1"):
		return "a"
	if has(hero_id, "b1"):
		return "b"
	return ""


static func _changed() -> void:
	Game.mark_dirty()
	Events.profile_changed.emit()


# ---------------------------------------------------------------- effects
## Every owned node's effects merged: numbers add up, ability mods are kept
## per slot, on_kill effects stack, aura/special/on_ult/ult_echo take the last.
static func effects(hero_id: String) -> Dictionary:
	var key := hero_id + "|" + ",".join(owned(hero_id))
	if _fx_cache.has(key):
		return _fx_cache[key]
	var fx := {"ab": {}, "on_kill": [], "on_hit": []}
	for nid in owned(hero_id):
		var e: Dictionary = node(hero_id, nid).get("effects", {})
		for k in e:
			match k:
				"ab":
					for m in e.ab:
						var slot := int(m.slot)
						if not fx.ab.has(slot):
							fx.ab[slot] = {}
						var dst: Dictionary = fx.ab[slot]
						for mk in m:
							if mk == "slot":
								continue
							if mk == "status":
								dst[mk] = m[mk]
							else:
								dst[mk] = float(dst.get(mk, 0.0)) + float(m[mk])
				"on_kill":
					fx.on_kill.append_array(e.on_kill)
				"on_hit":
					fx.on_hit.append(e.on_hit)
				"aura", "special", "on_ult", "ult_echo", "bonus_status":
					fx[k] = e[k]
				_:
					fx[k] = float(fx.get(k, 0.0)) + float(e[k])
	_fx_cache[key] = fx
	return fx


## Stat bonus used by Game.hero_stats (0.0 when nothing is owned).
static func stat(hero_id: String, key: String) -> float:
	if Game.profile.is_empty() or owned(hero_id).is_empty():
		return 0.0
	return float(effects(hero_id).get(key, 0.0))


## A hero ability's data with this hero's mastery modifiers applied (a copy).
static func ability_def(hero_id: String, slot: int, base: Dictionary) -> Dictionary:
	if Game.profile.is_empty() or owned(hero_id).is_empty():
		return base
	var m: Dictionary = effects(hero_id).ab.get(slot, {})
	if m.is_empty():
		return base
	var d := base.duplicate(true)
	for k in m:
		var v = m[k]
		match k:
			"dmg":
				d.dmg = float(d.get("dmg", 1.0)) * (1.0 + float(v))
			"cooldown":
				d.cooldown = float(d.cooldown) * (1.0 - clampf(float(v), 0.0, 0.6))
			"energy":
				d.energy = maxf(0.0, float(d.energy) + float(v))
			"radius", "range", "duration", "execute", "heal", "lifesteal":
				d[k] = float(d.get(k, 0.0)) + float(v)
			"count", "hits":
				d[k] = int(d.get(k, 1)) + int(v)
			"status":
				d.status = (v as Dictionary).duplicate()
			"status_power":
				if d.has("status"):
					var st: Dictionary = (d.status as Dictionary).duplicate()
					st.power = float(st.power) * (1.0 + float(v))
					d.status = st
			"buff_duration", "buff_mult":
				if d.has("buff"):
					var bf: Dictionary = (d.buff as Dictionary).duplicate()
					if k == "buff_duration":
						bf.duration = float(bf.duration) + float(v)
					else:
						bf.mult = float(bf.mult) + float(v)
					d.buff = bf
			"summon_hp", "summon_dmg":
				d[k] = float(v)
	d["mastery"] = true
	return d


# ---------------------------------------------------------------- text
static func t(key: String) -> String:
	return TranslationServer.translate(key)


static func fmt(key: String, args: Array) -> String:
	return t(key) % args


static func ability_name(hero_id: String, slot: int) -> String:
	var hd: Dictionary = DB.heroes[hero_id]
	var ids: Array = hd.abilities.duplicate()
	ids.append(hd.ultimate)
	return t("ability." + str(ids[clampi(slot, 0, ids.size() - 1)]))


static func _status_name(st: Dictionary) -> String:
	return t("status." + str(st.get("id", "")))


static func describe(hero_id: String, node_id: String) -> Array:
	var out: Array = []
	var e: Dictionary = node(hero_id, node_id).get("effects", {})
	var pct := func(v) -> int: return int(round(float(v) * 100.0))
	for k in e:
		var v = e[k]
		match k:
			"damage_pct", "health_pct", "defense_pct", "attack_speed", "move_speed", "crit", "crit_dmg", \
			"lifesteal", "cdr", "ult_mult", "dr", "thorns", "on_hit_execute":
				out.append(fmt("ht.fx." + k, [pct.call(v)]))
			"range_add", "energy_regen", "splash":
				out.append(fmt("ht.fx." + k, [float(v)]))
			"regen":
				out.append(fmt("ht.fx.regen", [float(v) * 100.0]))
			"multishot", "pierce", "chain":
				out.append(fmt("ht.fx." + k, [int(v)]))
			"revive":
				out.append(fmt("ht.fx.revive", [pct.call(v)]))
			"bonus_status":
				out.append(fmt("ht.fx.bonus_status", [pct.call(float(v.mult) - 1.0)]))
			"on_hit":
				if v.has("chance"):
					out.append(fmt("ht.fx.on_hit_chance", [pct.call(v.chance), _status_name(v.status)]))
				else:
					out.append(fmt("ht.fx.on_hit", [_status_name(v.status)]))
			"aura":
				out.append(fmt("ht.fx.aura", [float(v.radius)]))
				if v.has("drain"):
					out.append(t("ht.fx.aura_drain"))
			"on_ult":
				out.append(fmt("ht.fx.on_ult", [int(v.duration), pct.call(v.damage), pct.call(v.dr)]))
			"ult_echo":
				out.append(fmt("ht.fx.ult_echo", [float(v.delay), pct.call(v.mult)]))
			"on_kill":
				for ok in v:
					match str(ok.type):
						"explode": out.append(fmt("ht.fx.kill.explode", [float(ok.radius)]))
						"raise": out.append(fmt("ht.fx.kill.raise", [pct.call(ok.chance)]))
						"reset_cd": out.append(fmt("ht.fx.kill.reset_cd", [ability_name(hero_id, int(ok.slot))]))
						"energy": out.append(fmt("ht.fx.kill.energy", [int(ok.amount)]))
						"rampage": out.append(fmt("ht.fx.kill.rampage", [pct.call(ok.attack_speed), int(ok.max)]))
						"heal": out.append(fmt("ht.fx.kill.heal", [pct.call(ok.get("heal", 0.05))]))
			"ab":
				for m in v:
					var parts: Array = []
					for mk in m:
						var mv = m[mk]
						match mk:
							"slot": pass
							"dmg", "cooldown", "execute", "lifesteal", "status_power", "buff_mult", "summon_hp", "summon_dmg":
								parts.append(fmt("ht.ab." + mk, [pct.call(mv)]))
							"radius", "range", "duration", "buff_duration":
								parts.append(fmt("ht.ab." + mk, [float(mv)]))
							"count", "hits", "energy":
								parts.append(fmt("ht.ab." + mk, [int(mv)]))
							"status":
								parts.append(fmt("ht.ab.status", [_status_name(mv)]))
					out.append(fmt("ht.fx.ab", [ability_name(hero_id, int(m.slot)), ", ".join(parts)]))
			"special":
				out.append(describe_special(v))
	return out


static func describe_special(sp: Dictionary) -> String:
	var a: Dictionary = sp.ab
	var what := ""
	match str(a.type):
		"summon": what = fmt("ht.syn.summon", [int(a.count), t("ally." + str(a.unit))])
		"blink_strike": what = fmt("ht.syn.blink_strike", [int(a.hits)])
		"chain": what = fmt("ht.syn.chain", [int(a.count)])
		_: what = t("ht.syn." + str(a.type))
	if sp.type == "periodic":
		return fmt("ht.sp.periodic", [float(sp.every), what])
	return fmt("ht.sp.every_attacks", [int(sp.every), what])


# ---------------------------------------------------------------- dev
## Developer / balance helper (ignores cost and level): "a", "b", "a2b", "b2b",
## "trunk" for every hero, or "hell_knight:a,frost_mage:b".
static func dev_grant(spec: String) -> void:
	var s := state()
	var jobs: Array = []
	if ":" in spec:
		for part in spec.split(","):
			var kv := part.split(":")
			jobs.append([kv[0], kv[1]])
	else:
		for hid in hero_ids():
			jobs.append([hid, spec])
	for j in jobs:
		var ids: Array = ["core_1", "core_2", "core_3", "core_4", "core_5"]
		match str(j[1]):
			"a": ids += ["a1", "a2", "a3"]
			"b": ids += ["b1", "b2", "b3"]
			"a2b": ids += ["a1", "a2b", "a3"]
			"b2b": ids += ["b1", "b2b", "b3"]
		s.nodes[j[0]] = ids
