class_name TowerTree
extends RefCounted
## Tower Mastery: a permanent skill tree per tower type, bought with Crown
## Sigils earned from stages, stars, bosses and achievements.
##
## Design data lives in data/tower_tree.json (generated by
## tools/design/gen_tower_tree.py). Adding a tower = adding its node list
## there; adding a mechanic = adding an effect key here (apply) and, if it is a
## new behaviour, handling it in Tower / Projectile.
##
## Save format (profile.tower_tree):
##   {"earned": int, "nodes": {tower_id: [node_id, ...]}, "respecs": int, "init": true}
## Spent points are always recomputed from the owned nodes, so a save can never
## hold more spent than earned.

const EARN_FIRST_CLEAR := 1
const EARN_PER_STAR := 1
const EARN_BOSS := 2
const EARN_ACHIEVEMENT := 1
const EARN_ENDLESS_PER := 10          # one sigil per 10 waves of new endless best
const MAX_PEN := 0.8

static var _fx_cache: Dictionary = {}   # "tower_id|owned nodes" -> merged effects


# ---------------------------------------------------------------- state
static func data() -> Dictionary:
	return DB.tower_tree


static func state() -> Dictionary:
	var p: Dictionary = Game.profile
	if not p.has("tower_tree") or typeof(p.tower_tree) != TYPE_DICTIONARY:
		p["tower_tree"] = {}
	var s: Dictionary = p.tower_tree
	if not s.has("earned"): s["earned"] = 0
	if not s.has("nodes"): s["nodes"] = {}
	if not s.has("respecs"): s["respecs"] = 0
	if not s.get("init", false):
		# Existing saves get the sigils they would have earned so far.
		s["init"] = true
		s["earned"] = int(s.earned) + retroactive_points()
		Game.mark_dirty()
	return s


static func retroactive_points() -> int:
	var pts := 0
	for sid in Game.profile.get("stars", {}):
		var st := int(Game.profile.stars[sid])
		if st <= 0:
			continue
		pts += EARN_FIRST_CLEAR + st * EARN_PER_STAR
		var info := DB.stage_info(sid)
		if not info.is_empty() and info.data.get("boss", false):
			pts += EARN_BOSS
	for a in Game.profile.get("achievements", {}).values():
		pts += int(a.get("claimed", 0)) * EARN_ACHIEVEMENT
	pts += int(Game.profile.get("endless_best", 0)) / EARN_ENDLESS_PER
	return pts


static func earned() -> int:
	return int(state().earned)


static func spent() -> int:
	var total := 0
	for tid in state().nodes:
		total += spent_on(tid)
	return total


static func spent_on(tower_id: String) -> int:
	var total := 0
	for nid in owned(tower_id):
		var n := node(tower_id, nid)
		total += int(n.get("cost", 0))
	return total


static func available() -> int:
	return maxi(0, earned() - spent())


static func award(points: int, reason := "") -> void:
	if points <= 0:
		return
	state().earned = earned() + points
	_changed()
	Events.notify(tr_fmt("tt.sigils_gained", [points]) + ("" if reason == "" else "  (%s)" % reason), Color(1.0, 0.82, 0.35))


static func tr_fmt(key: String, args: Array) -> String:
	return TranslationServer.translate(key) % args


# ---------------------------------------------------------------- nodes
static func tower_ids() -> Array:
	var out: Array = []
	for tid in DB.tower_order:
		if data().get("towers", {}).has(tid):
			out.append(tid)
	return out


static func nodes(tower_id: String) -> Array:
	return data().get("towers", {}).get(tower_id, {}).get("nodes", [])


static func node(tower_id: String, node_id: String) -> Dictionary:
	for n in nodes(tower_id):
		if n.id == node_id:
			return n
	return {}


static func owned(tower_id: String) -> Array:
	return state().nodes.get(tower_id, [])


static func has(tower_id: String, node_id: String) -> bool:
	return node_id in owned(tower_id)


## "owned", "available", "no_points", "level", "requires", "blocked"
static func status(tower_id: String, node_id: String) -> String:
	if has(tower_id, node_id):
		return "owned"
	var n := node(tower_id, node_id)
	if n.is_empty():
		return "requires"
	if n.has("exclusive"):
		for o in owned(tower_id):
			var on := node(tower_id, o)
			if on.get("exclusive", "") == n.exclusive:
				return "blocked"
	var req: Array = n.get("requires_any", [])
	if not req.is_empty() and not req.any(func(r): return has(tower_id, r)):
		return "requires"
	if int(Game.profile.get("player_level", 1)) < int(n.get("level", 1)):
		return "level"
	if available() < int(n.get("cost", 1)):
		return "no_points"
	return "available"


static func buy(tower_id: String, node_id: String) -> bool:
	if status(tower_id, node_id) != "available":
		return false
	var s := state()
	if not s.nodes.has(tower_id):
		s.nodes[tower_id] = []
	s.nodes[tower_id].append(node_id)
	_changed()
	Events.track("tower_mastery")
	return true


static func respec_cost(tower_id := "") -> int:
	var pts := spent_on(tower_id) if tower_id != "" else spent()
	if pts <= 0:
		return 0
	var r: Dictionary = data().get("respec", {})
	var cost := maxi(int(r.get("min_gold", 100)), pts * int(r.get("gold_per_point", 40)))
	if tower_id == "":
		cost = int(cost * 0.8)       # resetting everything at once is a bit cheaper
	return cost


## Refunds every sigil spent on one tower (or on all towers) for gold.
static func respec(tower_id := "") -> bool:
	var cost := respec_cost(tower_id)
	if cost <= 0 or Game.gold() < cost:
		return false
	Game.add_gold(-cost)
	var s := state()
	if tower_id == "":
		s.nodes = {}
	else:
		s.nodes.erase(tower_id)
	s.respecs = int(s.respecs) + 1
	_changed()
	return true


static func has_capstone(tower_id: String) -> bool:
	for nid in owned(tower_id):
		if node(tower_id, nid).get("capstone", false):
			return true
	return false


static func mastery_tier(tower_id: String) -> int:
	## 0 none, 1 trunk only, 2 path chosen, 3 capstone.
	var o := owned(tower_id)
	if o.is_empty():
		return 0
	if has_capstone(tower_id):
		return 3
	if o.any(func(n): return n in ["a1", "b1"]):
		return 2
	return 1


static func chosen_path(tower_id: String) -> String:
	if has(tower_id, "a1"):
		return "a"
	if has(tower_id, "b1"):
		return "b"
	return ""


static func _changed() -> void:
	Game.mark_dirty()
	Events.profile_changed.emit()


# ---------------------------------------------------------------- effects
## All owned node effects of a tower merged into one dictionary.
static func effects(tower_id: String) -> Dictionary:
	var key := tower_id + "|" + ",".join(owned(tower_id))
	if _fx_cache.has(key):
		return _fx_cache[key]
	var fx := {"status": [], "special": {}}
	for nid in owned(tower_id):
		var e: Dictionary = node(tower_id, nid).get("effects", {})
		for k in e:
			match k:
				"status":
					fx.status.append(e[k])
				"special":
					fx.special = e[k]
				"unit", "mark", "bonus_status":
					fx[k] = e[k]
				"trap_splash":
					fx[k] = maxf(float(fx.get(k, 0.0)), float(e[k]))
				_:
					fx[k] = float(fx.get(k, 0.0)) + float(e[k])
	_fx_cache[key] = fx
	return fx


static func cost_mult(tower_id: String) -> float:
	if Game.profile.is_empty():
		return 1.0
	return 1.0 - clampf(float(effects(tower_id).get("cost", 0.0)), 0.0, 0.5)


static func build_cost(tower_id: String) -> int:
	return int(round(float(DB.towers[tower_id].levels[0].cost) * cost_mult(tower_id)))


## A tower level's stats with every mastery effect applied (a modified copy).
static func level_data(tower_id: String, level: int, branch: int) -> Dictionary:
	var base: Dictionary = DB.tower_level_data(tower_id, level, branch)
	if Game.profile.is_empty() or owned(tower_id).is_empty():
		return base
	return apply(tower_id, base, DB.tower_attr(tower_id, branch, "attack", "projectile"), effects(tower_id))


static func apply(_tower_id: String, base: Dictionary, atk: String, fx: Dictionary) -> Dictionary:
	var d := base.duplicate(true)
	var f := func(k: String) -> float: return float(fx.get(k, 0.0))
	# Beams deal damage per second, so attack speed turns into damage for them.
	var dm: float = 1.0 + f.call("dmg") + (f.call("rate") if atk == "beam" else 0.0)
	if d.has("dmg"):
		var arr: Array = d.dmg
		d.dmg = [float(arr[0]) * dm, float(arr[arr.size() - 1]) * dm]
	if d.has("rate") and atk != "beam":
		d.rate = float(d.rate) * (1.0 + f.call("rate"))
	if d.has("range"):
		d.range = float(d.range) * (1.0 + f.call("range"))
	if f.call("crit") > 0.0:
		d.crit = float(d.get("crit", 0.0)) + f.call("crit")
	if f.call("crit_mult") > 0.0:
		d.crit_mult = 2.0 + f.call("crit_mult")
	if f.call("pen") > 0.0:
		d.pen = minf(MAX_PEN, f.call("pen"))
	if f.call("multishot") > 0.0 and atk == "projectile":
		d.multishot = int(d.get("multishot", 1)) + int(f.call("multishot"))
	if f.call("splash") > 0.0 and atk in ["projectile", "artillery", "storm"]:
		d.splash = float(d.get("splash", 0.0)) + f.call("splash")
	if f.call("pierce") > 0.0:
		d.pierce = int(d.get("pierce", 0)) + int(f.call("pierce"))
	if f.call("chain") > 0.0 and atk == "chain":
		d.chain = int(d.get("chain", 2)) + int(f.call("chain"))
	if f.call("stun") > 0.0:
		d.stun_chance = float(d.get("stun_chance", 0.0)) + f.call("stun")
	if f.call("freeze") > 0.0:
		d.freeze_chance = float(d.get("freeze_chance", 0.0)) + f.call("freeze")
	if f.call("fear") > 0.0:
		d.fear_chance = float(d.get("fear_chance", 0.0)) + f.call("fear")
	if f.call("knockback") > 0.0 and atk == "pulse":
		d.knockback = float(d.get("knockback", 0.0)) + f.call("knockback")
	if f.call("ramp") > 0.0 and atk == "beam":
		d.ramp = float(d.get("ramp", 0.5)) + f.call("ramp")
	if f.call("air_bonus") > 0.0:
		d.air_bonus = float(d.get("air_bonus", 1.0)) + f.call("air_bonus")
	if f.call("heal_allies") > 0.0:
		d.heal_allies = float(d.get("heal_allies", 0.0)) + f.call("heal_allies")
	if f.call("execute") > 0.0:
		d.execute = f.call("execute")
	# Barracks
	if atk == "barracks":
		if f.call("soldiers") > 0.0:
			d.soldiers = int(d.get("soldiers", 3)) + int(f.call("soldiers"))
		if f.call("soldier_hp") > 0.0 and d.has("hp"):
			d.hp = float(d.hp) * (1.0 + f.call("soldier_hp"))
		if f.call("armor") > 0.0:
			d.armor = float(d.get("armor", 10)) + f.call("armor")
		if f.call("respawn") > 0.0:
			d.respawn = float(d.get("respawn", 10)) * (1.0 - clampf(f.call("respawn"), 0.0, 0.8))
		if f.call("lifesteal") > 0.0:
			d.lifesteal = float(d.get("lifesteal", 0.0)) + f.call("lifesteal")
		if fx.has("unit"):
			d.unit = fx.unit
	# Traps
	if atk == "trap":
		if f.call("traps") > 0.0:
			d.traps = int(d.get("traps", 2)) + int(f.call("traps"))
		if float(fx.get("trap_splash", 0.0)) > 0.0:
			d.trap_splash = float(fx.trap_splash)
	# Status effects: resolve relative powers, merge with the tower's own status.
	var avg_dmg := 0.0
	if d.has("dmg"):
		avg_dmg = (float(d.dmg[0]) + float(d.dmg[1])) * 0.5
	var sp: float = 1.0 + f.call("status_power")
	var sd: float = 1.0 + f.call("status_duration")
	var statuses: Array = []
	if d.has("status") and not (d.status as Dictionary).is_empty():
		statuses.append((d.status as Dictionary).duplicate())
	for st in fx.get("status", []):
		var s: Dictionary = (st as Dictionary).duplicate()
		if s.has("power_mult"):
			s.power = avg_dmg * float(s.power_mult)
			s.erase("power_mult")
		var merged := false
		for o in statuses:
			if o.id == s.id:
				o.duration = maxf(float(o.duration), float(s.duration))
				o.power = maxf(float(o.power), float(s.power))
				merged = true
		if not merged:
			statuses.append(s)
	for s in statuses:
		s.duration = float(s.duration) * sd
		if s.id in ["slow"]:
			s.power = minf(0.8, float(s.power) * sp)
		elif not s.id in ["stun", "freeze", "root", "fear"]:
			s.power = float(s.power) * sp
	if not statuses.is_empty():
		d.status = statuses[0]
		if statuses.size() > 1:
			d.extra_status = statuses.slice(1)
	if fx.has("mark"):
		var ex: Array = d.get("extra_status", [])
		ex.append({"id": "marked", "duration": float(fx.mark.duration), "power": float(fx.mark.power)})
		d.extra_status = ex
	if fx.has("bonus_status"):
		d.bonus_status = fx.bonus_status
	if not (fx.get("special", {}) as Dictionary).is_empty():
		d.special = fx.special
	d.mastery = true
	return d


# ---------------------------------------------------------------- text
## Human-readable lines describing a node's effects (localised).
static func describe(tower_id: String, node_id: String) -> Array:
	var n := node(tower_id, node_id)
	var out: Array = []
	var e: Dictionary = n.get("effects", {})
	var pct := func(v) -> int: return int(round(float(v) * 100.0))
	for k in e:
		var v = e[k]
		if k == "dmg" and float(v) < 0.0:
			out.append(tr_fmt("tt.fx.dmg_neg", [-pct.call(v)]))
			continue
		match k:
			"dmg", "rate", "range", "cost", "pen", "crit", "crit_mult", "stun", "freeze", "fear", "ramp", \
			"soldier_hp", "respawn", "lifesteal", "status_power", "status_duration", "air_bonus", "execute":
				out.append(tr_fmt("tt.fx." + k, [pct.call(v)]))
			"multishot", "pierce", "chain", "soldiers", "traps", "armor", "heal_allies":
				out.append(tr_fmt("tt.fx." + k, [int(v)]))
			"splash", "knockback", "trap_splash":
				out.append(tr_fmt("tt.fx." + k, [float(v)]))
			"mark":
				out.append(tr_fmt("tt.fx.mark", [pct.call(v.power), int(v.duration)]))
			"bonus_status":
				out.append(tr_fmt("tt.fx.bonus_status", [pct.call(float(v.mult) - 1.0)]))
			"unit":
				out.append(tr_fmt("tt.fx.unit", [TranslationServer.translate("ally." + str(v))]))
			"status":
				match str(v.id):
					"slow": out.append(tr_fmt("tt.fx.status.slow", [pct.call(v.get("power", 0.3))]))
					"burn": out.append(TranslationServer.translate("tt.fx.status.burn"))
					"root": out.append(tr_fmt("tt.fx.status.root", [float(v.duration)]))
					_: out.append(tr_fmt("tt.fx.status.other", [str(v.id)]))
			"special":
				out.append_array(describe_special(v))
	return out


static func describe_special(s: Dictionary) -> Array:
	var out: Array = []
	match str(s.type):
		"volley":
			out.append(tr_fmt("tt.sp.volley", [int(s.every), int(s.count)]))
		"empowered":
			out.append(tr_fmt("tt.sp.empowered", [int(s.every), int(round(float(s.dmg_mult) * 100.0))]))
		"barrage":
			out.append(tr_fmt("tt.sp.barrage", [int(s.every), int(s.count)]))
		"nova":
			out.append(tr_fmt("tt.sp.nova", [int(s.every)]))
			var st: Dictionary = s.get("status", {})
			if not st.is_empty():
				var key := "tt.sp.nova_" + str(st.id)
				if TranslationServer.translate(key) != key:
					out.append(TranslationServer.translate(key))
			if s.has("heal_pct"):
				out.append(tr_fmt("tt.sp.nova_heal", [int(round(float(s.heal_pct) * 100.0))]))
			if s.has("knockback"):
				out.append(TranslationServer.translate("tt.sp.nova_knock"))
	return out


# ---------------------------------------------------------------- dev
## Developer / balance-test helper (bypasses cost and level): "a" or "b" gives
## every tower the full trunk + that path (first mid-tier choice), "a2b"/"b2b"
## picks the alternative mid node, "trunk" only the trunk; "archer:a,mage:b"
## targets single towers.
static func dev_grant(spec: String) -> void:
	var s := state()
	var jobs: Array = []
	if ":" in spec:
		for part in spec.split(","):
			var kv := part.split(":")
			jobs.append([kv[0], kv[1]])
	else:
		for tid in tower_ids():
			jobs.append([tid, spec])
	for j in jobs:
		var ids: Array = ["core_dmg", "core_rate", "core_range", "core_cost", "core_spec"]
		match str(j[1]):
			"a": ids += ["a1", "a2", "a3"]
			"b": ids += ["b1", "b2", "b3"]
			"a2b": ids += ["a1", "a2b", "a3"]
			"b2b": ids += ["b1", "b2b", "b3"]
		s.nodes[j[0]] = ids
		s.earned = int(s.earned) + spent_on(j[0])
